/* Explicit data projection shared by extension and local service. Credentials never enter snapshots. */
globalThis.EchoSyncData = (() => {
  const pick = (o, names) => Object.fromEntries(names.split(' ').filter(k => o && Object.hasOwn(o, k) && ['string', 'number', 'boolean'].includes(typeof o[k])).map(k => [k, o[k]]));
  const strings = a => Array.isArray(a) ? a.filter(x => typeof x === 'string') : [];
  const progress=s=>({已收藏:'未联系',考虑中:'未联系',已投:'已投递',已读:'等待 HR',已回:'待我回复'}[s]||s);
  const state = s => ({ ...pick(s, 'stage nextAction updatedAt nextContactAt appointmentUncertain appointmentEvidence rejectionEvidence'), recruiterFocus: strings(s?.recruiterFocus), risks: strings(s?.risks), openQuestions: strings(s?.openQuestions) });
  const array=(v,fn)=>Array.isArray(v)?v.map(fn):[];
  const evidence=e=>pick(e,'source quote stance at requirement projectQuote url title');
  const check=c=>({...pick(c,'label kind direction verification researchState researchError score reason quote question userRequirement inputSignature stale'),evidence:array(c?.evidence,evidence)});
  const rating=r=>r?({...pick(r,'overall candidateFit preferenceFit known total'),core:{roleMatch:check(r.core?.roleMatch),skillFit:check(r.core?.skillFit)},concerns:array(r.concerns,check)}):undefined;
  const recommendation=r=>r?({analysisMetrics:pick(r.analysisMetrics,'modelCalls modelMs researchMs totalMs'),...pick(r,'group brief at stale analysisStatus analysisError researchError staleReason factKey inputSignature'),staleLabels:strings(r.staleLabels),rating:rating(r.rating),reasons:strings(r.reasons),evidence:array(r.evidence,evidence),gaps:strings(r.gaps),unknown:strings(r.unknown),hardChecks:array(r.hardChecks,check)}):undefined;
  const draft=d=>d?pick(d,'text review kind updatedAt conversationId'):undefined;
  const sources=v=>array(v,s=>pick(s,'kind url firstSeenAt lastSeenAt'));
  const decision=h=>h?({...pick(h,'id kind previousState reason note source evidence at feedbackState ruleVersion undone'),reasons:strings(h.reasons)}):null;
  const stats=(v,depth=0)=>{if(typeof v==='number'&&Number.isFinite(v))return v;if(depth>6||!v||typeof v!=='object')return undefined;return Array.isArray(v)?v.map(x=>stats(x,depth+1)):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,stats(x,depth+1)]).filter(([,x])=>x!==undefined));};
  const plain=(v,depth=0)=>{if(['string','number','boolean'].includes(typeof v))return typeof v==='string'?v.slice(0,2000):v;if(depth>6||!v||typeof v!=='object')return undefined;return Array.isArray(v)?v.slice(0,50).map(x=>plain(x,depth+1)).filter(x=>x!==undefined):Object.fromEntries(Object.entries(v).slice(0,50).map(([k,x])=>[k,plain(x,depth+1)]).filter(([,x])=>x!==undefined));};
  const event=e=>({...pick(e,'key source kind fingerprint at lastSeenAt count'),evidence:plain(e?.evidence)});
  const action=a=>a?pick(a,'id targetId label reason'):undefined;
  const requiredArrays=new Set(['records','conversations','dailySummaries','messages']);
  const clean=(v,key='')=>{if(v===undefined||v===null)return undefined;if(Array.isArray(v)){const out=v.map(x=>clean(x)).filter(x=>x!==undefined);return out.length||requiredArrays.has(key)?out:undefined;}if(typeof v==='object'){const out=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x,k)]).filter(([,x])=>x!==undefined));return Object.keys(out).length?out:undefined;}return v;};
  const card=c=>({hardFilterConflicts:strings(c.hardFilterConflicts),requirementRules:c.requirementRules?{hard:strings(c.requirementRules.hard),soft:strings(c.requirementRules.soft)}:undefined,hardChecks:array(c.hardChecks,check),scores:scores(c.scores),scoreInfo:pick(c.scoreInfo,'message retry'),...pick(c,'analysisStatus analysisError researchError staleReason scoreStatus scoreStage scoreError scoreInputSignature scoreCheckedAt id recordId duplicateOfId title company url location salary status notes score stale brief group stage waitingFor lastMessageAt nextAction kind reason dueAt'),primaryAction:action(c.primaryAction),lastScanEvent:event(c.lastScanEvent),rating:rating(c.rating),availability:pick(c.availability,'kind at reason source evidence'),archive:c.archive?pick(c.archive,'reason evidence at automatic previousStatus'):null,sources:sources(c.sources),reasons:strings(c.reasons),evidence:array(c.evidence,evidence),gaps:strings(c.gaps),unknown:strings(c.unknown),differences:array(c.differences,x=>pick(x,'label before after'))});
  const failure=f=>pick(f,'at item stage type url message taskKind');
  const cards=c=>c?({...pick(c,'generatedAt'),recommendations:array(c.recommendations,card),activeJobs:array(c.activeJobs,card),recentJobs:array(c.recentJobs,card),recentSuccesses:array(c.recentSuccesses,card),recentFailures:array(c.recentFailures,card),recentConfirmations:array(c.recentConfirmations,card),recentChatSuccesses:array(c.recentChatSuccesses,card),recentChatFailures:array(c.recentChatFailures,card),recentChatConfirmations:array(c.recentChatConfirmations,card),duplicateJobs:array(c.duplicateJobs,card),dismissedRecommendations:array(c.dismissedRecommendations,card),actions:array(c.actions,card),waiting:array(c.waiting,card),taskFailures:array(c.taskFailures,failure),runs:Object.fromEntries(['discover','patrol','generate'].filter(k=>c.runs?.[k]).map(k=>[k,{...pick(c.runs[k],'status partial at succeeded processed total error'),ignoredFailureKeys:strings(c.runs[k].ignoredFailureKeys),failures:array(c.runs[k].failures,failure),scopes:strings(c.runs[k].scopes),resultIds:strings(c.runs[k].resultIds),failedResultIds:strings(c.runs[k].failedResultIds),resultConversationIds:strings(c.runs[k].resultConversationIds),failedConversationIds:strings(c.runs[k].failedConversationIds),stats:stats(c.runs[k].stats)}]))}):undefined;
  function workflow(w) {
    if (!w) return undefined;
    return { ...pick(w, 'version'), strategy: { ...pick(w.strategy, 'goal tone'), matchedEvidence: strings(w.strategy?.matchedEvidence), focus: strings(w.strategy?.focus), avoidClaims: strings(w.strategy?.avoidClaims) }, evaluation: { ...pick(w.evaluation, 'passed'), refine: strings(w.evaluation?.refine), checks: Object.fromEntries(['jdMatch','personalization','truthfulness','conciseness','naturalness'].filter(k => w.evaluation?.checks?.[k]).map(k => [k, pick(w.evaluation.checks[k], 'pass reason refine')])) } };
  }
  function scores(s) {
    if (!s) return undefined;
    const group = (o, keys) => ({ ...pick(o, 'total'), ...Object.fromEntries(keys.split(' ').filter(k => o?.[k]).map(k => [k, pick(o[k], 'score reason')])) });
    return { ...pick(s, 'overall source'), job: group(s.job, 'roleMatch skillFit salary location company techStack growth interviewDifficulty time wlb'), company: group(s.company, 'industryScale prosCons salary overtime') };
  }
  function snapshot(raw) {
    for (const key of ['records', 'conversations', 'dailySummaries']) {
      if (!Array.isArray(raw[key])) throw new Error('同步缺少完整数据：' + key);
      if (raw[key].length > 10000) throw new Error('数据条目过多，请先导出归档');
    }
    for (const key of ['records', 'conversations']) {
      const ids = raw[key].map(x => x?.id);
      if (ids.some(id => typeof id !== 'string' || !id || id.length > 200) || new Set(ids).size !== ids.length) throw new Error('记录 ID 无效或重复');
    }
    const result = {
      records: raw.records.map(r => ({ ...pick(r, 'id platformJobKey discardAfter captureDurationMs title company companyType workAddress benefits industry companyDescription location salary size experience education description greeting hrActive hrActiveText hrActiveCheckedAt publishedText publishedAt notes url createdAt statusUpdatedAt appliedAt repliedAt discoveryState lastJobScanAt lastChatMessageAt lastChatScanAt nextAction nextActionAt greetingState greetingUpdatedAt greetingCopiedAt greetingSentAt scoreStatus scoreStage scoreError scoreInputSignature scoreAttemptSignature scoreJobSignature scoreCheckedAt'),...(r.status?{status:progress(r.status)}:{}),sources:sources(r.sources),availability:{...pick(r.availability,'kind at reason source'),evidence:plain(r.availability?.evidence)},communicationArchive:plain(r.communicationArchive),recommendation:recommendation(r.recommendation),linkedConversationIds:strings(r.linkedConversationIds),replyDraft:draft(r.replyDraft),generationDraft:draft(r.generationDraft),userDecision:pick(r.userDecision,'kind reason at'),decisionHistory:array(r.decisionHistory,h=>pick(h,'kind reason at')), matchPoints: strings(r.matchPoints), scores: scores(r.scores), workflow: workflow(r.workflow), conversationState: state(r.conversationState), statusHistory: array(r.statusHistory,h=>({...pick(h,'at'),status:progress(h?.status),evidence:plain(h?.evidence)})),greetingHistory:array(r.greetingHistory,h=>pick(h,'state at source evidence')) })),
      recycleJobKeys: array(raw.recycleJobKeys,x=>pick(x,'id platformJobKey title company salary')),
      dismissedJobKeys: array(raw.dismissedJobKeys,x=>pick(x,'id platformJobKey title company salary')),
      conversations: raw.conversations.map(c => ({ ...pick(c, 'id key platform sourceUrl counterparty jobTitle company roleQuality rawText linkedRecordId suggestedRecordId matchState updatedAt createdAt scanError analysisError handledFingerprint restoredFingerprint restoredHumanFingerprint'),confirmation:c.confirmation?{...pick(c.confirmation,'keepOnlyChat'),noCommunication:pick(c.confirmation.noCommunication,'fingerprint at'),routing:pick(c.confirmation.routing,'fingerprint status kind reason at'),identity:pick(c.confirmation.identity,'key at'),roles:array(c.confirmation.roles,x=>pick(x,'key role at')),lastMessageAt:pick(c.confirmation.lastMessageAt,'fingerprint value at'),appointment:pick(c.confirmation.appointment,'fingerprint value at')}:undefined,manualProgress:pick(c.manualProgress,'status at'),activity:{identityEvidence:pick(c.activity?.identityEvidence,'method key reason readerVersion at'),...pick(c.activity,'identityReliable rolesReliable automaticReliable messageFingerprint lastScannedAt lastMessageAt waitingFor reliable changed lastChangeObservedAt')},lastScanEvent:event(c.lastScanEvent),events:array(c.events,event),patrol:pick(c.patrol,'kind reason dueAt policy'),archive:c.archive?pick(c.archive,'reason evidence at automatic'):null,replyDraft:draft(c.replyDraft),messages: (Array.isArray(c.messages) ? c.messages : []).map(m => ({ role: ['candidate','hr','system'].includes(m.role) ? m.role : 'unknown', text: String(m.text || ''), ...pick(m, 'id timestamp sentAt roleSource timeText timeSource timeReliable') })), analysis: { ...pick(c.analysis, 'jobTitle company readStatus replied lastSpeaker roleConfidence summary status hrActive bottleneck suggestion'), conversationState: state(c.analysis?.conversationState) } })),
      profile: String(raw.settings?.profile ?? raw.profile ?? ''), preferences: String(raw.settings?.greetingPrompt ?? raw.preferences ?? ''),
      dailySummaries: raw.dailySummaries.map(s => ({...pick(s, 'date markdown ts'),actionCards:cards(s.actionCards),stats:s.stats?{...stats(s.stats),...pick(s.stats,'date')}:undefined,compare:array(s.compare,x=>({...stats(x),...pick(x,'label')})),usage:stats(s.usage)})),
      profiles:array(raw.profiles,p=>({...pick(p,'date markdown ts'),funnel:stats(p.funnel)})),
      agentNeedsInbox:strings(raw.agentNeedsInbox).slice(-50),
      agentConfig:{...pick(raw.agentConfig,'softText cities excludes minSalary ruleVersion followDays archiveDays autoArchive confirmedClassification'),softPreferences:array(raw.agentConfig?.softPreferences,p=>({...pick(p,'label sourceQuote version meaning question answer confirmed createdAt'),positiveSignals:strings(p.positiveSignals),negativeSignals:strings(p.negativeSignals),options:strings(p.options)})),hardRequirements:array(raw.agentConfig?.hardRequirements,p=>pick(p,'label meaning sourceQuote mode createdAt'))},
      agentRuleHistory:array(raw.agentRuleHistory,x=>({version:Number(x?.version)||0,at:Number(x?.at)||0,softText:String(x?.softText||''),softPreferences:array(x?.softPreferences,p=>({...pick(p,'label sourceQuote version meaning question answer confirmed createdAt'),positiveSignals:strings(p.positiveSignals),negativeSignals:strings(p.negativeSignals),options:strings(p.options)})),hardRequirements:array(x?.hardRequirements,p=>pick(p,'label meaning sourceQuote mode createdAt'))})).slice(-20)
    };
    result.records.forEach((r,i)=>{const original=raw.records[i];Object.assign(r,pick(original,'lastCompleteJobAt duplicateIgnoredKey'));r.mergeHistory=array(original.mergeHistory,h=>({at:h.at,conflicts:array(h.conflicts,x=>pick(x,'id field')),records:snapshot({records:h.records||[],conversations:[],dailySummaries:[]}).records}));r.userDecision=decision(original.userDecision);r.decisionHistory=array(original.decisionHistory,decision);r.hardConflictResolution=pick(original.hardConflictResolution,'kind signature at');r.statusEvidence=pick(original.statusEvidence,'source conversationId text at');r.nextActionEvidence=pick(original.nextActionEvidence,'source text at');r.sourceSnapshot=pick(original.sourceSnapshot,'title company companyType workAddress benefits industry companyDescription location salary size experience education url hrActive hrActiveText publishedText publishedAt applicationStatus applicationStatusText availability availabilityReason sourceKind sourceUrl companyDescriptionFingerprint descriptionFingerprint');r.events=array(original.events,event);r.lastScanEvent=event(original.lastScanEvent);r.availabilityHistory=array(original.availabilityHistory,x=>pick(x,'kind at reason source evidence'));});
    result.agentConfig.softPreferences.forEach((p,i)=>{p.mode=raw.agentConfig?.softPreferences?.[i]?.mode==='unrestricted'?'unrestricted':'requirement';});
    result.dailySummaries.forEach((s,i)=>{const source=raw.dailySummaries[i].actionCards;if(!source||!s.actionCards)return;Object.assign(s.actionCards,pick(source,'feedbackCount'));s.actionCards.lastDecision=source.lastDecision?pick(source.lastDecision,'id at'):null;s.actionCards.possibleDuplicates=strings(source.possibleDuplicates);s.actionCards.recommendations.forEach((c,j)=>Object.assign(c,pick(source.recommendations[j],'discoveryState decisionAt hrActive hrActiveText')));});
    result.records.forEach((r,i)=>{r.legacyReview=pick(raw.records[i].legacyReview,'originalStatus needsConfirmation reason');});
    result.conversations.forEach((c,i)=>{const original=raw.conversations[i];c.aliasIds=strings(original.aliasIds);c.aliasKeys=strings(original.aliasKeys);if(original.mergedHistory?.length)c.mergedHistory=snapshot({records:[],conversations:original.mergedHistory,dailySummaries:[]}).conversations;c.messageHistory=array(raw.conversations[i].messageHistory,m=>({...pick(m,'id text timestamp sentAt roleSource'),role:['candidate','hr'].includes(m.role)?m.role:'unknown'}));});
    return clean(result);
  }
  return { snapshot };
})();
