const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
function runtime(initial={},deps={},pages={}) {
  const store=clone(initial);let notifications=0,calls=0,created=0,removed=0;
  const chrome={runtime:{getURL:x=>'chrome-extension://test/'+x},storage:{local:{get:(keys,cb)=>cb(Object.fromEntries(keys.filter(k=>k in store).map(k=>[k,clone(store[k])]))),set:(d,cb)=>{if(pages.failSet?.(d)){chrome.runtime.lastError={message:'测试写入失败'};cb&&cb();chrome.runtime.lastError=null;return;}Object.assign(store,pages.storedTransform?pages.storedTransform(clone(d)):clone(d));cb&&cb();}}},notifications:{create:async()=>{notifications++;}},tabs:{
    create:async({url})=>{created++;return {id:7,url,status:'complete'};},remove:async ids=>{removed+=Array.isArray(ids)?ids.length:1;},get:async()=>({id:7,url:'https://www.liepin.com/message/',status:'complete'}),update:async()=>({id:7,status:'complete'}),query:async()=>[{id:7,url:pages.activeUrl||'https://www.liepin.com/message/'}],sendMessage:async(id,m,options)=>{calls++;if(pages.reply)return pages.reply(m,options);throw Error('mock unavailable');}
  },scripting:{executeScript:async()=>pages.frames}};
  const context={chrome,URL,crypto,console,Date,setTimeout:fn=>{queueMicrotask(fn);return 1;}};
  vm.runInNewContext(src('agent-core.js')+'\n'+src('agent-tasks.js'),context);
  const tasks=context.AgentTasks({json:async()=>({reasons:['证据匹配'],evidence:[{requirement:'插件',projectQuote:'插件'}],gaps:[],unknown:[]}),analyzeChat:async()=>({conversationState:{stage:'沟通中'}}),generate:async()=>({greeting:'你好',matchPoints:[]}),...deps});
  return {C:context.AgentCore,tasks,store,notifications:()=>notifications,calls:()=>calls,created:()=>created,removed:()=>removed};
}
async function settled(r){for(let i=0;i<100;i++){await new Promise(res=>setImmediate(res));const s=await r.tasks.handle({type:'AGENT_STATUS'});if(!s.running)return s.agentTask;}throw Error('task did not settle');}
async function main(){
  const r=runtime(),C=r.C,cfg=C.validateConfig({}),now=Date.now(),day=86400000;
  assert.equal(C.recordTime({createdAt:1,lastJobScanAt:3,greetingCopiedAt:2}),3);
  assert.deepEqual(['pending','candidate','skipped','dismissed','selected',''].map(C.decisionLabel),['待判断','候选','暂时跳过','暂不考虑','已选择','—']);
  const staleDone=runtime({agentTask:{id:'stale-done',kind:'discover',status:'running',cursor:0,queue:[]}});assert.equal((await staleDone.tasks.handle({type:'AGENT_STATUS'})).agentTask.status,'completed');assert.equal(staleDone.store.agentTask.status,'completed');
  const stale=runtime({agentTask:{id:'stale',kind:'discover',status:'running',cursor:0,queue:[{type:'job'}]}});assert.equal((await stale.tasks.handle({type:'AGENT_STATUS'})).agentTask.status,'interrupted');assert.equal(stale.store.agentTask.status,'interrupted');
  const pageDirection=C.directionFromPage('https://www.liepin.com/zhaopin/?key=AI&city=050020&workYearCode=0&currentPage=3&ckId=tracking');
  assert.equal(pageDirection.name,'AI');assert(new URL(pageDirection.url).searchParams.get('city')==='050020');
  assert(!pageDirection.url.includes('tracking'));assert.equal(new URL(pageDirection.url).searchParams.get('currentPage'),'0');
  assert.throws(()=>C.directionFromPage('https://liepin.com.evil.test/zhaopin/'));
  assert.equal(C.jobKey('https://www.liepin.com/a/78300095.shtml?x=1'),'liepin:a:78300095');
  assert.notEqual(C.jobKey('https://www.liepin.com/a/123.shtml'),C.jobKey('https://www.liepin.com/job/123.shtml'));
  assert.equal(new URL(C.directionFromPage('https://www.liepin.com/zhaopin/?newFilter=on&compId=company').url).searchParams.get('newFilter'),'on');
  assert.equal(C.jobKey('https://www.liepin.com/job/123.shtml?x=1'),C.jobKey('https://www.liepin.com/job/123.shtml?x=2'));
  assert.equal(C.jobKey('https://liepin.com.evil.test/job/123.shtml'),'');
  assert.equal(C.listKind('https://c.liepin.com/job/record/apply'),'apply');assert.equal(C.listKind('https://c.liepin.com/job/record/favorite'),'favorites');
  assert.throws(()=>C.validateConfig({followDays:7,archiveDays:3}));
  assert.throws(()=>C.validateConfig({directions:[{name:'x',url:'javascript:alert(1)'}]}));
  assert.equal(C.filter({description:'插件',salary:'8-12k',location:'广州'}, {...cfg,minSalary:15}).rejected.length,1);
  assert.equal(C.filter({description:'插件',salary:'面议'}, {...cfg,minSalary:15}).unknown.length,1);
  const records=[{id:'old',url:'https://www.liepin.com/job/123.shtml',title:'人工岗位名',notes:'重要备注',status:'Offer',greeting:'旧话术'}];
  C.mergeJob(records,{url:'https://www.liepin.com/job/123.shtml?x=1',title:'抓取新名称',description:'插件'}, {group:'match'});
  assert.equal(records.length,1);assert.equal(records[0].title,'人工岗位名');assert.equal(records[0].status,'Offer');assert.equal(records[0].greeting,'旧话术');
  assert.equal(C.recordById(records,'liepin:123'),records[0]);assert.equal(C.recordById(records,'https://www.liepin.com/job/123.shtml?other=1'),records[0]);
  const firstEvent=records[0].lastScanEvent.fingerprint;
  C.mergeJob(records,{url:'https://www.liepin.com/job/123.shtml?x=2',title:'抓取新名称',description:'插件'},null);
  assert.equal(records[0].lastScanEvent.kind,'duplicate');assert.equal(records[0].status,'Offer');assert.equal(records[0].lastScanEvent.fingerprint,firstEvent);
  C.applyAvailability(records[0],'unavailable',now,{source:'job-page',reason:'停止招聘'});assert.equal(records[0].status,'Offer');assert.equal(records[0].availability.kind,'unavailable');
  assert.equal(C.nextAction(records[0],[]).id,'toggleDetails');
  const axes={id:'axes',title:'产品',company:'甲',description:'JD',discoveryState:'candidate',status:'已投递',availability:{kind:'available'}};
  assert.equal(C.nextAction(axes,[]).label,'查看当前进展');assert.equal(axes.status,'已投递');assert.equal(axes.discoveryState,'candidate');
  assert.equal(C.nextAction({...axes,status:'未联系',greetingState:'draft',greeting:'你好'},[]).label,'查看并修改话术');assert.equal(C.nextAction({...axes,status:'未联系',greetingState:'copied',greeting:'你好'},[]).id,'openJob');
  const grouped=C.feedbackGroups([{title:'甲岗',company:'甲',decisionHistory:[{id:'f1',reasons:['工资'],feedbackState:'pending'},{id:'f2',reasons:['薪资'],feedbackState:'pending'}]}]);
  assert.equal(grouped[0].label,'薪资');assert.equal(grouped[0].count,2);assert.equal(grouped[0].examples[0],'甲 · 甲岗');
  C.mergeJob(records,{url:'https://www.liepin.com/job/456.shtml',title:'发现'},{});assert.equal(C.managed(records).length,1);
  const detected=[];C.mergeJob(detected,{url:'https://www.liepin.com/job/457.shtml',title:'采购',company:'甲',description:'JD',applicationStatus:'已投递',applicationStatusText:'已投递'},{});assert.equal(detected[0].status,'已投递');assert.equal(detected[0].discoveryState,'pending');assert.equal(detected[0].statusEvidence.source,'job-page');
  const chat={conversationKey:'www.liepin.com|c',identityReliable:true,messages:[{id:'m1',role:'candidate',roleSource:'explicit',text:'请问进度',sentAt:now-15*day}],text:'请问进度',roleQuality:'high'};
  const activity=C.activity(chat,{},now),item={activity,analysis:{conversationState:{}}};
  assert.equal(C.patrol(item,cfg,now).kind,'archive');
  const rescanned=C.activity(chat,activity,now+day);assert.equal(rescanned.changed,false);assert.equal(rescanned.lastMessageAt,activity.lastMessageAt);
  assert.equal(rescanned.lastChangeObservedAt,activity.lastChangeObservedAt);
  assert.equal(C.patrol({...item,activity:{...activity,waitingFor:'user'}},cfg,now).kind,'reply');
  assert.equal(C.patrol({...item,activity:{...activity,lastMessageAt:null}},cfg,now).kind,'unknown');
  assert.equal(C.patrol({...item,activity:{...activity,reliable:false}},cfg,now).kind,'unknown');
  assert.equal(C.patrol({...item,scanError:'网络'},cfg,now).kind,'unknown');
  assert.equal(C.patrol({...item,analysis:{conversationState:{nextContactAt:now+day}}},cfg,now).kind,'waiting');
  assert.equal(C.patrol({...item,analysis:{conversationState:{appointmentUncertain:true}}},cfg,now).kind,'unknown');
  const replyItem={id:'reply-chat',activity:{reliable:true,waitingFor:'user'},messages:[{role:'hr',roleSource:'explicit',text:'收到，想再了解你的项目'}],analysis:{status:'待我回复',conversationState:{stage:'沟通中'}}};assert.equal(C.conversationStatus(replyItem,{status:'已投递'}).status,'待我回复');
  const interviewItem={...replyItem,messages:[{role:'hr',roleSource:'explicit',text:'邀请你参加视频面试'}],analysis:{status:'面试中',conversationState:{stage:'面试安排'}}};assert.equal(C.conversationStatus(interviewItem,{status:'已投递'}).status,'面试中');
  const statusRec={status:'已投递',statusHistory:[]};assert.equal(C.applyStatus(statusRec,'待我回复',now,true,{source:'chat'}),true);assert.equal(statusRec.repliedAt,now);assert.equal(C.applyStatus(statusRec,'等待 HR',now+1,true),true);
  assert.equal(C.applyStatus(statusRec,'错误状态',now+2),false);assert.equal(statusRec.status,'等待 HR');
  const stateAxes={};C.applyGreeting(stateAxes,'draft',now,{source:'generator'});C.applyGreeting(stateAxes,'draft',now+1,{source:'generator'});C.applyGreeting(stateAxes,'copied',now+2,{source:'record'});assert.equal(stateAxes.greetingHistory.length,2);assert.equal(stateAxes.greetingCopiedAt,now+2);assert.equal(stateAxes.status,'已准备话术');assert.equal(C.normalizeStatus('已回'),'待我回复');
  C.applyNextAction(stateAxes,'等待招聘方',now,{source:'chat'});assert.equal(stateAxes.nextActionEvidence.source,'chat');
  const decision={id:'d1',kind:'candidate',reason:'',reasons:[],note:'',feedbackState:'none',at:now};assert.equal(C.applyDecision(stateAxes,decision),true);assert.equal(C.applyDecision(stateAxes,{...decision,id:'d2'}),false);assert.equal(stateAxes.decisionHistory.length,1);assert.equal(C.undoDecision(stateAxes),true);assert.equal(stateAxes.discoveryState,'pending');
  C.addEvent(stateAxes,'job:search','job-observed','same',now,{text:'首次读取'});C.addEvent(stateAxes,'job:search','job-observed','same',now+1,{text:'重复读取'});const timeline=C.timeline(stateAxes);assert.equal(timeline.filter(x=>x.kind==='event').length,1);assert(timeline.some(x=>x.title.includes('用户判断')));assert(timeline.some(x=>x.title.includes('话术')));assert(timeline.some(x=>x.title.includes('招聘进度')));
  const edited=runtime({records:[{id:'legacy',platformJobKey:'liepin:700',url:'https://www.liepin.com/job/700.shtml',title:'旧标题',status:'未联系',notes:'',recommendation:{stale:false}}]});
  await edited.tasks.handle({type:'AGENT_UPDATE_RECORD',id:'liepin:700',patch:{title:'新标题',notes:'人工备注',status:'已投递'},source:'test'});assert.equal(edited.store.records[0].title,'新标题');assert.equal(edited.store.records[0].notes,'人工备注');assert.equal(edited.store.records[0].status,'已投递');assert.equal(edited.store.records[0].recommendation.stale,true);assert(edited.C.timeline(edited.store.records[0]).some(x=>x.title==='岗位资料修改'));
  for(let i=0;i<40;i++)C.addSource(stateAxes,'search','https://www.liepin.com/zhaopin/?page='+i,now+i);assert.equal(stateAxes.sources.length,40); // v0.18.10 preserves existing source history.
  const state=runtime({agentConfig:{autoArchive:true},records:[{id:'job',status:'Offer',notes:'保留'}],conversations:[{id:'c',key:chat.conversationKey,linkedRecordId:'job'}],dailySummaries:[{ts:now,markdown:'原有鼓励',stats:{total:1},compare:[{新增:1}]}]});
  await state.tasks.saveScan(chat,{conversationState:{stage:'经验验证',nextAction:'跟进'}},'https://www.liepin.com/message/');
  assert.equal(state.store.records[0].status,'Offer');assert.equal(state.store.records[0].notes,'保留');assert.equal(state.store.records[0].lastChatMessageAt,chat.messages[0].sentAt);
  assert.equal(state.store.conversations[0].archive,undefined); // Offer is protected in both scan and batch paths.
  await state.tasks.handle({type:'AGENT_LINK',conversationId:'c',recordId:'job'});
  assert.equal(state.store.records[0].linkedConversationIds[0],'c');
  assert.equal(state.store.records[0].status,'Offer');
  const liveChat={conversationKey:'www.liepin.com|live',identityReliable:true,messages:[{id:'hr1',role:'hr',roleSource:'explicit',text:'收到，想再了解你的项目',sentAt:now-1000}],text:'收到',roleQuality:'high'},live=runtime({records:[{id:'live-job',title:'产品',company:'甲',status:'已投递'}],conversations:[{id:'live-conversation',key:liveChat.conversationKey,linkedRecordId:'live-job'}]});await live.tasks.saveScan(liveChat,{status:'待我回复',conversationState:{stage:'沟通中'}},'');assert.equal(live.store.records[0].status,'待我回复');assert.equal(live.store.records[0].statusEvidence.source,'chat');
  await state.tasks.handle({type:'AGENT_ACTION',action:'restore',id:'c'});
  await state.tasks.saveScan(chat,{conversationState:{stage:'错误的新分析'}},'https://www.liepin.com/message/');
  assert(!state.store.conversations[0].archive);assert.equal(state.store.conversations[0].analysis.conversationState.stage,'经验验证');
  await state.tasks.refresh(true);await state.tasks.refresh(true);
  assert.equal(state.notifications(),1);assert.equal(state.store.dailySummaries.length,1);assert.equal(state.store.dailySummaries[0].markdown,'原有鼓励');assert.equal(state.store.dailySummaries[0].compare[0].新增,1);
  const discovery=runtime({settings:{apiKey:'test',deepseekConsent:true,profile:'插件'},agentConfig:{directions:[{name:'测试',url:'https://www.liepin.com/zhaopin/?key=x'}]}},{},{reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'插件岗位',company:'测试公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/job/123.shtml'}],available:1,scope:'测试列表'}});
  await discovery.tasks.handle({type:'AGENT_START',kind:'discover'});const completed=await settled(discovery);
  assert.equal(completed.status,'completed');assert.equal(discovery.store.records.length,1);assert.equal(discovery.store.records[0].discoveryState,'pending');assert(discovery.removed()>0);
  await discovery.tasks.handle({type:'AGENT_ACTION',action:'generate',id:'liepin:123'});
  assert.equal(discovery.store.records[0].discoveryState,'pending');assert.equal(discovery.store.records[0].greeting,'你好');
  const rejectedDraft=runtime({settings:{apiKey:'test',deepseekConsent:true},records:[{id:'candidate',title:'候选岗位',company:'甲',description:'JD',discoveryState:'candidate'}]}, {generate:async()=>{const e=new Error('质量检查未通过');e.result={greeting:'待修改草稿'};throw e;}});await assert.rejects(()=>rejectedDraft.tasks.handle({type:'AGENT_ACTION',action:'generate',id:'candidate'}),/质量检查未通过/);assert.equal(rejectedDraft.store.records[0].discoveryState,'candidate');assert.equal(rejectedDraft.store.records[0].generationDraft.text,'待修改草稿');
  await discovery.tasks.handle({type:'AGENT_START',kind:'discover'});await settled(discovery);assert.equal(discovery.store.records.length,1);
  let reads=0;const partial=runtime({settings:{apiKey:'test',deepseekConsent:true,profile:'插件'},agentConfig:{directions:[{name:'测试',url:'https://www.liepin.com/zhaopin/?key=x'}]}},{},{reply:m=>{if(m.type==='EXTRACT_JOB'){reads++;return reads<=4?{ok:true,job:{title:'缺公司'}}:{ok:true,job:{title:'正常岗位',company:'测试公司',description:'插件'}};}return {ok:true,items:[{url:'https://www.liepin.com/job/201.shtml'},{url:'https://www.liepin.com/job/202.shtml'}],available:2,scope:'测试列表'};}});await partial.tasks.handle({type:'AGENT_START',kind:'discover'});const partialDone=await settled(partial);assert.equal(partialDone.status,'completed');assert.equal(partialDone.stats.failed,1);assert.equal(partial.store.records.length,1);assert.equal(partial.store.agentRuns.discover.failures[0].stage,'读取详情');assert.equal(partial.C.cards(partial.store.records,[],partial.store.agentRuns).taskFailures.length,1);
  const finalize=runtime({settings:{apiKey:'test',deepseekConsent:true,profile:'插件'},agentConfig:{directions:[{name:'测试',url:'https://www.liepin.com/zhaopin/?key=x'}]}},{},{failSet:d=>'dailySummaries' in d,reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'岗位',company:'公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/job/203.shtml'}],available:1,scope:'测试列表'}});await finalize.tasks.handle({type:'AGENT_START',kind:'discover'});const finalizeTask=await settled(finalize);assert.equal(finalizeTask.status,'paused');assert.match(finalizeTask.lastError,/结果整理失败/);assert.equal(finalize.store.agentRuns.discover.status,'paused');
  const denied=runtime({settings:{apiKey:'test',deepseekConsent:false}});await denied.tasks.handle({type:'AGENT_START',kind:'patrol'});assert.equal((await settled(denied)).status,'paused');assert.equal(denied.calls(),0);
  const failing=runtime({settings:{apiKey:'test',deepseekConsent:true}});await failing.tasks.handle({type:'AGENT_START',kind:'patrol'});assert.equal((await settled(failing)).status,'paused');
  assert(failing.store.agentRuns.patrol.error.includes('unavailable'));
  // Paused tasks retain the cursor; the same item can resume after the page becomes readable.
  let failOnce=true;
  const resumed=runtime({settings:{apiKey:'test',deepseekConsent:true},agentConfig:{directions:[{name:'x',url:'https://www.liepin.com/zhaopin/'}]}},{},{reply:m=>{if(failOnce)throw Error('登录失效');return m.type==='EXTRACT_JOB'?{ok:true,job:{title:'x',company:'测试公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/job/789.shtml'}],available:1,scope:'1页'};}});
  await resumed.tasks.handle({type:'AGENT_START',kind:'discover'});assert.equal((await settled(resumed)).cursor,0);
  failOnce=false;await resumed.tasks.handle({type:'AGENT_RESUME'});assert.equal((await settled(resumed)).status,'completed');
  // A stop request during page processing survives the checkpoint and resume continues the queue.
  let stopAtList=true, stopping;
  stopping=runtime({settings:{apiKey:'test',deepseekConsent:true},agentConfig:{directions:[{name:'x',url:'https://www.liepin.com/zhaopin/'}]}},{},{reply:async m=>{if(stopAtList){stopAtList=false;await stopping.tasks.handle({type:'AGENT_STOP'});}return m.type==='EXTRACT_JOB'?{ok:true,job:{title:'x',company:'测试公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/job/777.shtml'}],available:1,scope:'1页'};}});
  await stopping.tasks.handle({type:'AGENT_START',kind:'discover'});const stopped=await settled(stopping);assert.equal(stopped.status,'paused');assert.equal(stopped.cursor,1);
  await stopping.tasks.handle({type:'AGENT_RESUME'});assert.equal((await settled(stopping)).status,'completed');
  const compact=C.cards([{id:'x',discoveryState:'pending',recommendation:{inputSignature:'private repeated input',group:'match'}}],[]);
  assert(!JSON.stringify(compact).includes('private repeated input'));
  // Summary rendering escapes model content and keeps all three sections.
  const ui={AgentCore:C};vm.runInNewContext(src('agent-ui.js'),ui);
  const html=ui.EchoAgentUI.cards({recommendations:[{id:'"',title:'<script>',reasons:[],gaps:[],unknown:[]}],actions:[],waiting:[]});
  assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes('待我回复'));assert(html.includes('回收站'));
  assert(src('app.js').includes('summaryCharts(s.stats) + renderCompare(s.compare)'));assert(!src('app.js').includes('AgentCore.cards(latestData.records'));assert(src('app.js').includes("box.innerHTML=EchoAgentUI.cards"));
  let pageListener;
  const links=Array.from({length:25},(_,i)=>({href:'https://www.liepin.com/job/'+(100+i)+'.shtml?track=x',innerText:'岗位'+i,closest:()=>null,getBoundingClientRect:()=>({width:100,height:30})}));
  const pageContext={URL,location:{hostname:'www.liepin.com',pathname:'/zhaopin/',href:'https://www.liepin.com/zhaopin/'},document:{body:{innerText:'岗位列表'},querySelector:selector=>selector.includes('job-list')?({querySelector:()=>null,querySelectorAll:()=>links}):null,querySelectorAll:selector=>selector==='a[href]'?links:[]},chrome:{runtime:{onMessage:{addListener:fn=>{pageListener=fn;}}}}};
  vm.runInNewContext(src('agent-page.js'),pageContext);
  const adapterCall=m=>new Promise(res=>pageListener({type:'AGENT_PAGE',...m},{},res));
  links[0].href='https://www.liepin.com/a/78300095.shtml?track=x';
  const listing=await adapterCall({action:'jobs'});
  assert.equal(listing.items[0].url,'https://www.liepin.com/a/78300095.shtml');
  assert.equal(listing.ok,true);assert.equal(listing.items.length,25);assert.equal(listing.available,25);assert(!listing.items[0].url.includes('?')); // Worker batches the retained queue, not the adapter.
  const row={innerText:'招聘方',className:'sessionItem active',getBoundingClientRect:()=>({width:120,height:40}),getAttribute:k=>k==='data-key'?'session-42':null};
  pageContext.document.querySelectorAll=selector=>selector.includes('.conversation-item')?[row]:[];
  row.attributes=[{name:'class'},{name:'title',value:'private-person'}];row.children=[];row.tagName='DIV';
  const structure=await adapterCall({action:'diagnose'});
  assert.equal(structure.candidates,1);assert(!JSON.stringify(structure).includes('private-person'));assert(!JSON.stringify(structure).includes('招聘方'));
  const chats=await adapterCall({action:'chats'});
  assert.equal(chats.items[0].key,'session-42');
  assert.equal(pageContext.echoChatIdentity().key,'session-42');
  row.className='sessionItem inactive';assert.equal(pageContext.echoChatIdentity(),null);
  const auto=runtime({records:[{id:'job',title:'内容 Agent',company:'公司A',status:'Offer',notes:'保留'}]});
  const matched=await auto.tasks.saveScan(chat,{jobTitle:'内容Agent',company:'公司A',conversationState:{nextAction:'确认安排'}},'');
  assert.equal(matched.linkedRecordId,'job');assert.equal(auto.store.records[0].status,'Offer');
  assert.equal(auto.store.records[0].nextAction,'打招呼已满48小时，未收到招聘方回复');
  assert.equal(C.matchRecord([{title:'产品',company:'甲'},{title:'产品',company:'甲'}],{jobTitle:'产品',company:'甲'}),null);
  const historical=runtime({records:[{id:'job',title:'产品',company:'甲'}],conversations:[{id:'history',jobTitle:'产品',company:'甲',analysis:{conversationState:{nextAction:'沟通'}}}]});
  assert.equal((await historical.tasks.handle({type:'AGENT_AUTO_LINK',conversationId:'history'})).linkedRecordId,'job');
  const framed=runtime({settings:{apiKey:'x',deepseekConsent:true}}, {}, {frames:[{frameId:0},{frameId:9}],reply:(m,options)=>{
    if(m.action==='chats')return {ok:true,items:options.frameId===9?[{key:'c',label:'招聘方'}]:[],available:1,scope:'可见会话'};
    assert.equal(options.frameId,9);
    if(m.action==='openChat')return {ok:true,selectedKey:'c'};
    if(m.type==='EXTRACT_CHAT')return {ok:true,chat};
    throw Error('unexpected page call');
  }});
  await framed.tasks.handle({type:'AGENT_START',kind:'patrol'});
  assert.equal((await settled(framed)).status,'completed');
  assert.equal(framed.store.conversations.length,1);
  assert.equal(framed.store.agentRuns.patrol.stats.added,1);assert.equal(framed.store.agentRuns.patrol.resultConversationIds.length,1);
  const patrolCards=framed.C.cards([],framed.store.conversations,framed.store.agentRuns);assert.equal(patrolCards.recentChatConfirmations.length,1);assert.equal(patrolCards.recentChatFailures.length,0);
  const oldShape=runtime({records:[{id:'kept',title:'内容产品',company:'公司甲',status:'Offer'}],conversations:[{id:'legacy',linkedRecordId:'deleted',analysis:{jobTitle:'内容产品',company:'公司甲'}}]});
  assert.equal((await oldShape.tasks.handle({type:'AGENT_AUTO_LINK',conversationId:'legacy'})).linkedRecordId,'kept');
  const missingJob=runtime({records:[],conversations:[{id:'new',analysis:{jobTitle:'产品',company:'乙'}}]});
  await missingJob.tasks.handle({type:'AGENT_AUTO_LINK',conversationId:'new'});
  assert.equal(missingJob.store.records.length,0);
  const createMessage={type:'AGENT_CREATE_LINK',conversationId:'new',title:'产品',company:'乙'};
  await assert.rejects(()=>missingJob.tasks.handle(createMessage),/请先打开岗位详情/);
  assert.equal(missingJob.store.records.length,0);
  assert.equal(missingJob.store.conversations[0].linkedRecordId,null);
  const single=runtime({settings:{apiKey:'x',deepseekConsent:true,profile:'插件'}},{},{activeUrl:'https://www.liepin.com/job/903.shtml',reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'当前岗位',company:'测试公司',description:'插件'}}:{ok:true}});
  await single.tasks.handle({type:'AGENT_START',kind:'discover',currentJob:true});
  assert.equal((await settled(single)).status,'completed');
  assert.equal(single.store.records.length,1);assert.equal(single.store.records[0].discoveryState,'pending');assert.equal(single.store.records[0].sources[0].kind,'current');assert.equal(single.created(),0);
  const inverse=runtime({settings:{apiKey:'x',deepseekConsent:true,profile:'插件'},conversations:[{id:'orphan',key:'www.liepin.com|orphan',jobTitle:'当前岗位',company:'测试公司',linkedRecordId:null,matchState:'unlinked',activity:{lastMessageAt:123}}]},{},{activeUrl:'https://www.liepin.com/job/904.shtml',reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'当前岗位',company:'测试公司',description:'插件'}}:{ok:true}});
  await inverse.tasks.handle({type:'AGENT_START',kind:'discover',currentJob:true});await settled(inverse);assert.equal(inverse.store.conversations[0].linkedRecordId,'liepin:904');assert.equal(inverse.store.records[0].linkedConversationIds[0],'orphan');
  const current=runtime({settings:{apiKey:'x',deepseekConsent:true,profile:'插件'}},{},{activeUrl:'https://www.liepin.com/zhaopin/?filter=actual',reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'文控岗',company:'测试公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/a/78300095.shtml',title:'文控岗'}],available:1,scope:'实际列表'}});
  await current.tasks.handle({type:'AGENT_START',kind:'discover',currentPage:true});
  assert.equal((await settled(current)).status,'completed');
  assert.equal(current.store.records[0].id,'liepin:a:78300095');
  await current.tasks.handle({type:'AGENT_ACTION',action:'dismiss',id:'liepin:a:78300095'});
  assert.equal(current.C.cards(current.store.records,[]).dismissedRecommendations.length,1);
  await current.tasks.handle({type:'AGENT_ACTION',action:'restoreRecommendation',id:'liepin:a:78300095'});
  assert.equal(current.C.cards(current.store.records,[]).recommendations.length,1);
  const apply=runtime({settings:{apiKey:'x',deepseekConsent:true,profile:'插件'}},{},{activeUrl:'https://c.liepin.com/job/record/apply',reply:m=>m.type==='EXTRACT_JOB'?{ok:true,job:{title:'已投岗位',company:'测试公司',description:'插件'}}:{ok:true,items:[{url:'https://www.liepin.com/job/901.shtml'}],available:1,scope:'应聘记录'}});await apply.tasks.handle({type:'AGENT_START',kind:'discover',currentPage:true});assert.equal((await settled(apply)).status,'completed');assert.equal(apply.store.records[0].sources[0].kind,'apply');assert.equal(apply.store.records[0].status,'已投递');assert(apply.store.records[0].appliedAt);
  const progressed=[{id:'p',url:'https://www.liepin.com/job/902.shtml',status:'面试中',discoveryState:'selected'}];current.C.mergeJob(progressed,{url:progressed[0].url,title:'岗位',company:'公司',description:'JD',sourceKind:'apply',sourceUrl:'https://c.liepin.com/job/record/apply'});assert.equal(progressed[0].status,'面试中');
  let provisionalAnalyses=0;
  const provisionalChat={...chat,identityReliable:false,selectionVerified:true,identityEvidence:{method:'unverified',reason:'列表摘要与最后有效消息尚未对应'}};
  const provisional=runtime({settings:{apiKey:'x',deepseekConsent:true},agentConfig:{autoArchive:true}},{analyzeChat:async()=>{provisionalAnalyses++;return {conversationState:{stage:'沟通中'}};}},{reply:m=>{
    if(m.action==='chats')return {ok:true,items:[{key:'c',label:'临时身份'}],available:1,scope:'临时'};
    if(m.action==='openChat')return {ok:true,selectedKey:'c'};
    return {ok:true,chat:provisionalChat};
  }});
  for(let repeat=0;repeat<2;repeat++){await provisional.tasks.handle({type:'AGENT_START',kind:'patrol'});assert.equal((await settled(provisional)).status,'completed');}
  assert.equal(provisional.store.conversations.length,1);assert.equal(provisionalAnalyses,1);
  assert.equal(provisional.store.agentRuns.patrol.stats.duplicates,1);
  assert.equal(provisional.store.conversations[0].patrol.kind,'unknown');assert(!provisional.store.conversations[0].archive);
  delete provisionalChat.identityEvidence;
  await provisional.tasks.handle({type:'AGENT_START',kind:'patrol'});await settled(provisional);
  assert.equal(provisionalAnalyses,1);assert(provisional.store.agentTask.errors.some(e=>String(e.message).includes('读取器未返回身份')));assert.equal(provisional.store.conversations.length,1);
  const preferenceText='更在意双休，希望有人带';let ratedInput='';
  const personal=runtime({settings:{apiKey:'test',deepseekConsent:true,profile:'插件'},agentConfig:{minSalary:15},records:[{id:'pref-job',title:'产品',company:'甲',description:'插件。双休。导师带教。',salary:'15-20k',discoveryState:'pending',recommendation:{},notes:'保留',scores:{overall:3}}]}, {json:async(system,input)=>{
    if(system.startsWith('将用户表达'))return {preferences:[{label:'双休',sourceQuote:'双休'},{label:'有人带',sourceQuote:'希望有人带'},{label:'高薪',sourceQuote:'高薪'}]};
    ratedInput=input;return {brief:'经历相关，工作节奏值得了解',reasons:['匹配'],evidence:[{requirement:'插件',projectQuote:'插件'}],rating:{roleMatch:{score:4,reason:'职责相关',quote:'插件'},skillFit:{score:4,reason:'项目经历',quote:'插件'},concerns:[{label:'双休',kind:'meets',reason:'JD明确双休',evidence:[{source:'description',quote:'双休',stance:'positive'}]},{label:'有人带',kind:'meets',reason:'有导师',evidence:[{source:'description',quote:'导师带教',stance:'positive'}]}]}};
  }});
  const preferences=await personal.tasks.handle({type:'AGENT_PREFERENCES',text:preferenceText});assert.equal(preferences.length,2);
  assert.equal(personal.store.agentConfig.softPreferences,undefined); // Parsing does not silently save.
  await personal.tasks.handle({type:'AGENT_CONFIG',config:{softText:preferenceText,softPreferences:preferences.map(p=>({...p,confirmed:true}))}});
  assert.equal(personal.store.agentConfig.minSalary,15);
  await personal.tasks.handle({type:'AGENT_START',kind:'discover',refreshRecommendations:true});
  assert.equal((await settled(personal)).status,'completed');
  assert(ratedInput.includes('有人带'));assert.equal(personal.store.records[0].recommendation.rating.overall,4.4);
  assert.equal(personal.store.records[0].scores.overall,3);assert.equal(personal.store.records[0].notes,'保留');assert.equal(personal.calls(),0);
  const unknown=C.recommendationRating({roleMatch:{score:4,reason:'相关',quote:'插件'},skillFit:{score:4,reason:'相关',quote:'插件'},concerns:[{label:'双休',score:5,reason:'猜测',quote:'不存在'}]}, {description:'插件'},[{label:'双休'}],[{}]);
  assert.equal(unknown.concerns[0].score,null);assert.equal(unknown.overall,4);
  assert.equal(C.recommendationRating({}, {description:'插件'},[],[]).overall,null);
  await personal.tasks.handle({type:'AGENT_CONFIG',config:{cities:'广州'}});assert.equal(personal.store.agentConfig.softPreferences.length,2);
  pageContext.document.body.innerText='安全验证';
  assert.equal((await adapterCall({action:'jobs'})).ok,false);
  console.log('agent smoke passed: filters, merging, incremental scans, timeout safety, restore, digest, worker, generation, errors');
}
module.exports={runtime,settled};
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});

